### ISSUE TITLE
[Important] WPGlobus compatibility issue with ACF

### ISSUE THREAD

**Issue by nlamkr** [WPGlobus/WPGlobus#101]
If the post has custom fields created via ACF  & if that post is edited via page builder (Elementor), it throws the following fatal error. 

```
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/html/wp-content/plugins/wpglobus/includes/vendor/acf/class-wpglobus-acf.php:226
Stack trace:
#0 /var/www/html/wp-content/plugins/wpglobus/includes/vendor/acf/class-wpglobus-acf.php(193): WPGlobus_Acf_2::handle_acf_fields(Array)
#1 /var/www/html/wp-content/plugins/wpglobus/includes/class-wpglobus-config-vendor.php(427): WPGlobus_Acf_2::get_post_meta_fields(7652, false)
#2 /var/www/html/wp-content/plugins/wpglobus/includes/class-wpglobus-config-vendor.php(475): WPGlobus_Config_Vendor::get_post_meta_fields('*', Array)
#3 /var/www/html/wp-content/plugins/wpglobus/includes/class-wpglobus-config-vendor.php(83): WPGlobus_Config_Vendor::parse_config()
#4 /var/www/html/wp-content/plugins/wpglobus/includes/class-wpglobus-config-vendor.php(95): WPGlobus_Config_Vendor->__construct(Object(WPGlobus_Config_Builder))
#5 /var/www/html/wp-content/plugins/wpglobus/includes/class-wpglobus-config.php(968): WPGlobus_Config_Vendor::get_instance(Object(WPGlobu in /var/www/html/wp-content/plugins/wpglobus/includes/vendor/acf/class-wpglobus-acf.php on line 226
```

The error is thrown from the  static method `handle_acf_fields( $post_meta_fields )` inside `/plugins/wpglobus/includes/vendor/acf/class-wpglobus-acf.php`, where the variable `$WPGlobus_Vendor_Acf` is null but  it is being used to call another method.  If the post has no ACF fields, the above method won't process the  `$post_meta_fields`, thus no error is thrown.

It would be very nice if you could fix it & roll-out a plugin update asap. Thanks.

**Recommended quick fix:**
Check if the variable `$WPGlobus_Vendor_Acf` is null on `/plugins/wpglobus/includes/vendor/acf/class-wpglobus-acf.php line-no. 225`

**Comment by tivnet** [comment]
The issue should be fixed in version 2.10.10
