### ISSUE TITLE
How to translate Categories? 

### ISSUE THREAD

**Issue by wudong** [WPGlobus/WPGlobus#11]
Wondering how the categories is translated? couldn't see it in the Category editor. Thanks a lot.

**Comment by tivnet** [comment]
@wudong Yes, they should be translatable. Are you talking about categories for regular Posts, or maybe for some custom types?

**Comment by wudong** [comment]
Just normal categories. 
While exploring it, I found a blank field without label under the "name" field, in the quick edit for categories, and change this seems getting the the translation done. 

And then I see that in the full Edit of the category, the name is changed something like:
{:zh}中英文化{:}{:en}UK/China{:}

Does this kind of string will be translated anywhere if the plugin installed? The reason why I ask is I have some thrid-party plugin also need translated.

**Comment by tivnet** [comment]
@wudong If you see that {:}... string instead of the tabs then there is something preventing normal run of our javascript code. Wonder if you see any JS errors in the console...

**Comment by wudong** [comment]
console seems clean!

**Comment by tivnet** [comment]
Strange. If you give us a temporary admin access, we'll take a look. Use this form http://www.wpglobus.com/pg/contact-us/ to send us a private message.

**Comment by wudong** [comment]
alright.
