### ISSUE TITLE
Way to disable in certain instances?

### ISSUE THREAD

**Issue by lukedanielson** [WPGlobus/WPGlobus#13]
Just wondering if there is a way to disable translating in certain instances, ie when calling a query for a post term.

Is there a way to force the english locale, then make the query, then set the locale back to what it was?  Or is there a way to add a filter, make the query and then remove the filter?

Thank you for the great plugin!

**Comment by tivnet** [comment]
@lukedanielson Hi Luke, would you like to show a piece of code where you need WPGlobus to be temporarily disabled?
Thank you!

**Comment by lukedanielson** [comment]
Sure thing.  It would be when getting terms either basic wp functions or apart of woocommerce related wp functions:

```php
 $categories = get_terms( 'category', array( 'orderby' => 'count', 'fields' => 'names' ) );
```

Or

```php
$flavors = wc_get_product_terms( $product->id, 'pa_flavor', array( 'fields' => 'names' ) );
```

**Comment by tivnet** [comment]
Can this help?
https://github.com/WPGlobus/WPGlobus/blob/develop/includes/class-wpglobus.php#L2393-L2397

**Comment by lukedanielson** [comment]
Yes, exactly!  However that gets me the string of the terms in each language, ie:

```php
'{:en}Apple{:}{:es}Manzana{:}' 
```

Is there a way to specify which lang version to use?

Thanks again for your help.

**Comment by tivnet** [comment]
Now you can call the `WPGlobus_Filters::filter__text` and pass the language parameter.

**Comment by lukedanielson** [comment]
Ahah.  Yes, that indeed worked. Thank you!
