### ISSUE TITLE
I get same links for all languages - without country code

### ISSUE THREAD

**Issue by swist666** [WPGlobus/WPGlobus#14]
Hi in my site i get links for languages like this:
```
<link rel="alternate" hreflang="en-US" href="//localhost:3000/"/>
<link rel="alternate" hreflang="es-ES" href="//localhost:3000/"/>
<link rel="alternate" hreflang="de-DE" href="//localhost:3000/"/>
<link rel="alternate" hreflang="fr-FR" href="//localhost:3000/"/>
<link rel="alternate" hreflang="ru-RU" href="//localhost:3000/"/>
```

And trying to go //localhost:3000/es ends with 404 error. Any ideas what could be wrong?

**Comment by tivnet** [comment]
The "wrong" part is that you are using localhost:3000 for development instead of setting a normal name.

WPGlobus localizes only URLs with a real domain name. Not "localhost".

**Comment by swist666** [comment]
ok, I get it. Will //address.com:3000/ work?

**Comment by tivnet** [comment]
Did not try myself, but some users reported that it worked for them.

Just curious, why do you need port 3000? What's wrong with 80?

**Comment by swist666** [comment]
address.com:3000 does not work. It's just mine dev setup. Nvmd addres.dev wors so case is closed.

**Comment by tivnet** [comment]
Sorry for that. Glad you have this solved. Thank you!
