### ISSUE TITLE
Language switch

### ISSUE THREAD

**Issue by matyushen** [WPGlobus/WPGlobus#16]
Hey guys, awesome plugin, thanks for your work! 
Is there a way to put a language switch manually in the theme? I mean not in a sidebar. Didn't find anything on this in the docs.
Thanks!

**Comment by tivnet** [comment]
@matyushen Thanks Nikita, you can either extract a portion of our widget code, or you can use https://wordpress.org/plugins/amr-shortcode-any-widget/ to put it anywhere.

**Comment by matyushen** [comment]
Thanks! I would go with `the_widget( 'WPGlobusWidget' );`

**Comment by tivnet** [comment]
If that's your own theme, then - of course.
