### ISSUE TITLE
After update yoast seo plugin WPGlobus not working

### ISSUE THREAD

**Issue by sudarshan955** [WPGlobus/WPGlobus#17]

**Comment by alexgff** [comment]
Yoast SEO version 3 is not supported yet. We are working on the upgrade.

**Comment by lukedanielson** [comment]
I also have an issue with this, using both Yoast SEO and WPGlobus.  What all has to be done WPGlobus to support Yoast 3.0?

**Comment by tivnet** [comment]
Yoast 3 has too many bugs. It's still unstable, breaks many plugins and themes and not recommended for production use.
https://wordpress.org/support/view/plugin-reviews/wordpress-seo?filter=1

**Comment by lukedanielson** [comment]
Gotcha.  I will stick with version 2.3.5 until 3 is more stable.  Thanks!

**Comment by alexgff** [comment]
@sudarshan955, @lukedanielson 
Now WPGlobus 1.4 supports Yoast SEO 3
