### ISSUE TITLE
Problem with Chrome-tabs title!

### ISSUE THREAD

**Issue by aLEX12213** [WPGlobus/WPGlobus#20]
There is a problem with Google Chrome tab titles when Yoast SEO is on. You can see it on http://cgstudio.org/gallery/. When i switch Yoast SEO "of" the problem is disappearing. All other plugins is switched off too. Thanks. Sorry for my English.

**Comment by aLEX12213** [comment]
<title>{:ru}Галерея{:}{:en}Gallery{:} | CGStudio.org</title>

**Comment by tivnet** [comment]
Алекс, откройте support ticket на www.wpglobus.com
Спасибо
