### ISSUE TITLE
Data in ACF Repeater fields isn't being saved on first attempt

### ISSUE THREAD

**Issue by unireverse** [WPGlobus/WPGlobus#22]
When ever you add a new row in a ACF repeater field and save the post, the data inside the repeater field fails to save. The result is empty rows within the repeater field. It specifically happens when **adding** new rows to the repeater. If I re-enter the data in the empty rows after the first attempt and then save, it will be successful.

Its mentioned that this issue is in your backlog according to this post:
https://wordpress.org/support/topic/acf-text-field-in-acf-repeater-is-not-saved

I'm curious what's the status on it. I can try to fix it as well. Any direction is appreciated.

**Comment by unireverse** [comment]
I figured out the problem, and here's the pull request with the fix:
https://github.com/WPGlobus/WPGlobus/pull/24

**Comment by alexgff** [comment]
@unireverse I made fixes into develop branch you can check

**Comment by unireverse** [comment]
Confirmed that its fixed.
I'll close out my pull request.

**Comment by pixelarbeit** [comment]
Seems like this is an issue again.
I'm running ACF Pro Version 5.6.5 and WPGlobus Version 1.9.6 and can not save repeater values on first try.

**Comment by pixelarbeit** [comment]
So I figured out, that ACF-Pro is cloning the whole `tr` and just replaces the IDs. As it doens't look into `data-source-id`-Attribute, it doesn't get replaced with the right ID and WPGlobus fails to match the input fields.
