### ISSUE TITLE
Siteorigin Page Builder support

### ISSUE THREAD

**Issue by bash88** [WPGlobus/WPGlobus#25]
Hi Guys,

I'd like to use WPGlobus in a website which also uses Page Builder. I've read the threads in the support forum and also the statement about reaching an agreement with Siteorigin to work towards compatibility. I thought the last post about this was 5 months ago.

Is there any update on this? I prefer WPGlobus over Polylang, but if there won't be support for Page Builder any time soon I will have to go for Polylang.

Thanks in advance for your response,
Bas

**Comment by tivnet** [comment]
Hi @bash88 ,

Unfortunately, there is no good news.

They never came back, so we do not have any immediate plans to support it.

Polylang, of course, do not have problems with that. If you are OK with post duplication - go with them, of course.

Thank you!

**Comment by bash88** [comment]
Hi @tivnet ,

I'm really not ok with post duplication. That's why I want to use WPGlobus. I see there are a lot of people asking for compatibility with Page Builder. Can't you make a little more effort to communicate with SiteOrigin?

In [this thread](https://siteorigin.com/thread/homepage-with-wpglobus-plugin/) they even stated they would be happy to assist you in getting the plugin to work with PageBuilder.


Bas

**Comment by tivnet** [comment]
Let's make a petition :)

Seriously, we cannot do anything good without them wanting to have WPGlobus support. I would be more than happy seeing a long line of developers looking to contact us. So far, the line is very short :(

But, we are quite young, so there is still hope....

Thanks, Bas
