### ISSUE TITLE
WPGlobus Plus - ACF WYSIWYG Removing empty <p>

### ISSUE THREAD

**Issue by unireverse** [WPGlobus/WPGlobus#26]
Hi there,

Is there a particular reason for removing empty \<p\> elements inside WYSIWYG fields when saving a post?
I'm specifically referring to this part of the code in includes/js/wpglobus-plus-acf.js:
```js
saveContent: function( editor, language ) {
	var c = editor.getContent().replace(/<p>\s*<\/p>/g, '' ); // remove empty p
	api.content[editor.id] = WPGlobusCore.getString( api.content[editor.id], c, language );
},
```

Its causing issues with creating linebreaks and my client requires them for formatting the content.
Could there be an option to disable it?

**Comment by alexgff** [comment]
@unireverse 
filter for disable/enable removing empty p will be added in WPGlobus Plus 1.1.11

**Comment by unireverse** [comment]
Thanks!

**Comment by alexgff** [comment]
WPGlobus Plus 1.1.11 is out
