### ISSUE TITLE
Version not updating in plugins list

### ISSUE THREAD

**Issue by lukedanielson** [WPGlobus/WPGlobus#30]
For some reason, the plugin version number will not update in the plugins admin page.  I downloaded the latest (1.5.0) version, removed the old version (1.4.0) and replaced with the new, yet it still says 1.4.0. 

Wondering if this is some sort of tag issue.

Thoughts?

/wp-admin/plugins.php:
<img width="786" alt="screen shot 2016-04-22 at 11 07 48 am" src="https://cloud.githubusercontent.com/assets/1958560/14750667/d0f06dac-087a-11e6-9d6f-3f4f74bf6d5e.png">

/wp-content/plugins/wpglobus/changelog.md:
<img width="740" alt="screen shot 2016-04-22 at 11 11 11 am" src="https://cloud.githubusercontent.com/assets/1958560/14750703/fb4de494-087a-11e6-864f-f510bc5b4787.png">

The wp meta field '_site_transient_update_plugins' keeps adding 1.4.0 as opposed to 1.5.0

**Comment by alexgff** [comment]
@lukedanielson 
Screenshot 1 is for Woocommerce WPGlobus
http://www.wpglobus.com/extensions-archive/woocommerce/
Screenshot 2 is for WPGlobus
http://wordpress.org/plugins/wpglobus/
