### ISSUE TITLE
Secure non-secure elements

### ISSUE THREAD

**Issue by technima** [WPGlobus/WPGlobus#32]
The WPGlobus plugin's options page is not secure because it embeds a non-secure element.

To remedy this issue, the non-secure element should be included locally with the plugin, or the non-secure element should be offered via a secure site which would require securing wpglobus.com (I suggest using a Let's Encrypt certificate).

Here is the the non-secure element:
http://www.wpglobus.com/app/uploads/2015/08/wpglobus-plus-logo-150x150.png

For users who have secured their Wordpress sites, this element yields a "mixed content" warning. The major browsers have made promises to eventually block even passive mixed content such as this, so this fix should be a priority.

**Comment by tivnet** [comment]
@technima Thanks for reporting this. Will fix a.s.a.p.

**Comment by tivnet** [comment]
Fixed in `develop` branch.
https://github.com/WPGlobus/WPGlobus/commit/b4d92f93567b5b29d325d9eedd7ea74c9077bbe0
