### ISSUE TITLE
stream_socket_client() unable to connect to tcp://www.wpglobus.com:80

### ISSUE THREAD

**Issue by lukedanielson** [WPGlobus/WPGlobus#34]
Hey I'm getting a tcp connection timeout in my WordPress admin dashboard:

    Warning
    :  stream_socket_client(): unable to connect to 
        tcp://www.wpglobus.com:80 (Connection timed out) in 
        /var/www/staging/public/wp/wp-includes/class-wp-http-streams.php
        on line 150

I am running nginx 1.10.0 and have opened the appropriate firewall ports in UFW:

    80/tcp                     ALLOW IN    Anywhere 

Is the wpglobus.com domain not responding correctly, or is it a server configuration issue on my end?

Running WP Globus version `1.6.3` on Wordpress `4.5.3`

Thanks for the help!

**Comment by tivnet** [comment]
Hi @lukedanielson 

The WPGlobus website is working fine, as far as I see.

**Comment by lukedanielson** [comment]
I've stopped seeing the error, so perhaps there was just a slight downtime moment.  Thank you!

**Comment by tivnet** [comment]
Let's call it a "connectivity problem". There was no downtime on our servers. :)
