### ISSUE TITLE
[MailChimp] Warning: Attempt to assign property of non-object 

### ISSUE THREAD

**Issue by nmohanan** [WPGlobus/WPGlobus#35]
Hi I have installed wordpress and wp globus plugin, i also installed mail-chimp plugin for wordpress. after submitting newsletter form i am getting this error.

Warning: Attempt to assign property of non-object in /var/www/project/wp-content/plugins/wpglobus/includes/vendor/class-wpglobus-mailchimp-for-wp.php on line 52. when i disable wpglobus, the error will not occur. Please help

**Comment by alexgff** [comment]
@nmohanan fixed

**Comment by nmohanan** [comment]
After updating this code it is not working, it is not sending any emails through mailchimp.

When i commented these lines from the code 
from wp-globus_controller.php
require_once 'vendor/class-wpglobus-mailchimp-for-wp.php';
	WPGlobus_MailChimp_For_WP::controller();
Emails are coming correctly but issue is the mail chimp language switch wont work. 
{:en}Email address{:}{:no}Epostadresse{:}

If possible plese let me know the fix

**Comment by tivnet** [comment]
@nmohanan When it does not send the emails, is there any error in logs?

**Comment by tivnet** [comment]
@nmohanan Got info in #37

**Comment by nmohanan** [comment]
It is showing Please select at least one list. The mail will not send, when i comment this line the email will send correctly, but language is not working

**Comment by nmohanan** [comment]
Submitted with errors: no_lists_selected

**Comment by tivnet** [comment]
Released in WPGlobus 1.6.2
