### ISSUE TITLE
After updating with the latest code no emails receiving from mail chimp.

### ISSUE THREAD

**Issue by nmohanan** [WPGlobus/WPGlobus#36]
After updating this code it is not working, it is not sending any emails through mailchimp.

When i commented these lines from the code 
from wp-globus_controller.php
require_once 'vendor/class-wpglobus-mailchimp-for-wp.php';
WPGlobus_MailChimp_For_WP::controller();
Emails are coming correctly but issue is the mail chimp language switch wont work. 
{:en}Email address{:}{:no}Epostadresse{:}

**Comment by tivnet** [comment]
See #37

**Comment by nmohanan** [comment]
Issue fixed by latest update in git https://github.com/WPGlobus/WPGlobus/issues/37
