### ISSUE TITLE
Regarding WPglobus plugin conflict with Mailchimp

### ISSUE THREAD

**Issue by tbenny** [WPGlobus/WPGlobus#37]
The emails are not been recieved via mailchimp unless we disable WPglobus plugin and also on the form it shows "Please select at least one list." even though the list is selected in form settings in mailchimp .
Is the function filter__data in the /wp-content/plugins/wpglobus/includes/vendor/class-wpglobus-mailchimp-for-wp.php causing the issue.

**Comment by tivnet** [comment]
@tbenny Thanks for reporting.

Related: #35

**Comment by tbenny** [comment]
when we log the event by addding add_filter( 'mc4wp_debug_log_level', function() { return 'debug'; } ); in file includes/wpglobus-controller.php we are getting the error " INFO: Form 14538 > Submitted with errors: no_lists_selected ,this is the error" in error log file mc4wp-debug.log in uploads

**Comment by tbenny** [comment]
Thanks alex the fix is working

**Comment by tivnet** [comment]
Released in WPGlobus 1.6.2
