### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by slaFFik** [WPGlobus/WPGlobus#38]
After running `php7cc` we found out these issues:

```
File: .../plugins/wpglobus/lib/ReduxCore/inc/browser.php
> Line 191: PHP 4 constructors are now deprecated
    function Browser($useragent = '')
    {
    }


File: .../plugins/wpglobus/includes/class-wpglobus-filters.php
> Line 810: Nested by-reference foreach loop, make sure there is no iteration over the same array
    foreach ($_value as &$_deep_value) {
    }
```

First one is not critical, and is related to Redux more (can you ping them as well regarding this?), the 2nd one - might and might not be broken, need to check in the source code.

**Comment by tivnet** [comment]
Related: https://wordpress.org/support/topic/compatibility-with-php-7-12

**Comment by tivnet** [comment]
ToDo:
- [ ] Upgrade embedded Redux Core

**Comment by tivnet** [comment]
11eff2ec4b8d0df7b297ef430c9065a4329811f3

**Comment by tivnet** [comment]
@slaFFik The "nested" loop is OK. General refactoring of that code part is planned, so for now I can only suggest ignoring that warning.
