### ISSUE TITLE
WPGlobus is not translating on my page only my wordpress admin bar.

### ISSUE THREAD

**Issue by KoolAide187** [WPGlobus/WPGlobus#40]
WPGlobus is not translating on my page only my wordpress admin bar.
http://www.echocalls.com 
Please take a look.

**Comment by KoolAide187** [comment]
Also, one more thing. I'd like to get 100/100 user experience on my website with the pagespeed tool and i'm 97/100 with pagespeed atm. It's telling me my tap targets are too small. How can I make the flags bigger with CSS?

**Comment by alexgff** [comment]
> WPGlobus is not translating on my page only my wordpress admin bar.
Do you mean automatic translation ?
