### ISSUE TITLE
External Links break

### ISSUE THREAD

**Issue by Quarkmus** [WPGlobus/WPGlobus#41]
If I add an external link to a menu and change the language the extrenal links break.
Example:
https://b19.rwth-aachen.de/ there is a link to 
http://old.b19.rwth-aachen.de/proposal/create
which become http://old.b19.rwth-aachen.de/en/proposal/create
in english.

Also if I link to a media in the menu like:
https://b19.rwth-aachen.de/wp-content/uploads/2016/06/Mitglieder-Aufnahmeantrag-%C3%BCberarbeitet-detail-englisch.pdf
switching to english the link becomes 
https://b19.rwth-aachen.de/en/wp-content/uploads/2016/06/Mitglieder-Aufnahmeantrag-%C3%BCberarbeitet-detail-englisch.pdf

**Comment by alexgff** [comment]
@Quarkmus 
you can use filter 'wpglobus_nav_menu_objects' to make your own URL 
( e.g. without  language code) for some menu items

**Comment by Quarkmus** [comment]
Thanks for the help,
in case someone else has such a problem:
http://www.wpglobus.com/faq/how-can-i-prevent-to-localize-custom-link-in-menu/

I had to edit the file  `wpglobus/includes/wpglobus-controller.php`
And add the following lines:

> add_filter( 'wpglobus_nav_menu_objects', 'filter__wpglobus_nav_menu_objects' );
> 
> function filter__wpglobus_nav_menu_objects( $menu_items ) {
> 	
> 	if ( WPGlobus::Config()->default_language == WPGlobus::Config()->language ) {
> 		return $menu_items;
> 	}
> 	
> 	foreach ( $menu_items as $key => $item ) 
> 	{
> 		if ($menu_items[$key]->object_id == 284)
> 		{
> 			$menu_items[ $key ]->url = WPGlobus_Utils::localize_url( $menu_items[ $key ]->url, de );
> 		}	
> 	}	
> 	
> 	return $menu_items;
> }

**Comment by alexgff** [comment]
@Quarkmus
Right way to add custom code this is the editing of functions.php file of child theme or custom plugin.

**Comment by alexgff** [comment]
BTW
> $menu_items[ $key ]->url = WPGlobus_Utils::localize_url( $menu_items[ $key ]->url, de );

$menu_items[ $key ]->url = WPGlobus_Utils::localize_url( $menu_items[ $key ]->url, 'de' );
