### ISSUE TITLE
Does not work for page subtitles

### ISSUE THREAD

**Issue by Antairez** [WPGlobus/WPGlobus#44]
Hello, I'm using WPGLobus with Visual Composer, with "WPGlobus for WPBakery Visual Composer" plugin enabled. Everything works fine except for the page subtitle, which doesn't have a language dependent option, so it will stay the same for all languages.

![image](https://cloud.githubusercontent.com/assets/7032726/21568766/2db82258-cef2-11e6-8e70-b8c7dc6ad408.png)

**Comment by alexgff** [comment]
@Antairez 
for this case we have module "Editor" in WPGlobusPlus
To get more info please read
http://www.wpglobus.com/product/wpglobus-plus/#editor
