### ISSUE TITLE
Syntax error in wpglobus-filters.php on line 137

### ISSUE THREAD

**Issue by bartcerneels** [WPGlobus/WPGlobus#45]
Parse error: syntax error, unexpected ‘&’ in /wordpress/wp-content/plugins/wpglobus/includes/class-wpglobus-filters.php on line 137

After update to wpglobus release 1.7.7 on wordpress 4.7.1 install.
PHP version: 5.3.3

[Wordpress support forum post](https://wordpress.org/support/topic/error-after-latest-update-6)

**Comment by tivnet** [comment]
It's not in the source code
https://github.com/WPGlobus/WPGlobus/blob/develop/includes/class-wpglobus-filters.php#L137

Something happened with WP itself, I afraid. Checking it.

**Comment by tivnet** [comment]
Will reply on WP forum
