### ISSUE TITLE
Backend Advertisements

### ISSUE THREAD

**Issue by mattyhead** [WPGlobus/WPGlobus#49]
I'm seeing an advertisement displaying in the backend whenever WPGlobus is enabled.
![wpglobus_ad](https://cloud.githubusercontent.com/assets/1293373/23724778/075fd5ce-041c-11e7-833e-949751851639.PNG)

Either disabling or uninstalling WPGlobus removes it.  Reinstalling from WP plugin search or cloning from github and activating brings it back.  I don't have anything by the guys referenced in the ads.

If this were a typical "buy our stuff and we'll stop showing you ads" scenario, you would state it clearly, so I'm concerned either I have an XSS-derived problem that just happens to be in your data or (more worrying) you may have taken in code that doesn't do what you think it does.  I'll be looking into that first scenario, but I thought it wise to inquire about that scenario I'm inclined to discount:  Are you showing admin-ads intentionally?  Can we remove them with a purchase?

Thanks.

**Comment by tivnet** [comment]
@mattyhead This ad comes from the Redux Framework which we (and many other developers) are using to create the options panel. As far as I know, the ad appears only once after the plugin activation. We do not like it either, but at this point, we are not able to replace Redux Framework with something else.

**Comment by mattyhead** [comment]
Thank you for letting me know!  Sorry you guys are saddled with that... FYI I find the message is persisting, though not interfering.  The worst so far is RF's failure to distinguish between "your" and "you're".

**Comment by tivnet** [comment]
@mattyhead Try this in your config file:

    $GLOBALS['redux_notice_check'] = 1;

**Comment by mattyhead** [comment]
Grazie!

**Comment by tivnet** [comment]
Di niente :)

That $GLOBAL is in the recent WPGlobus upgrade (1.7.9), so you do not need to set it yourself.
