### ISSUE TITLE
Page update function does not work from non-default language

### ISSUE THREAD

**Issue by nanderh** [WPGlobus/WPGlobus#56]
When editing a page in a non-default language (e.g. default is English and Dutch is secondary, while editing the Dutch version) the Update page function does not work.

To reproduce:
- Edit an existing page
- Switch to secondary language
- Change content
- Select Update page
- Page reloads without the changes being reflected

**Comment by tivnet** [comment]
@nanderh Not enough information. Please submit a Help Desk request from the WPGlobus admin menu so we know your environment. Thanks.
