### ISSUE TITLE
.po file strings aren't translated

### ISSUE THREAD

**Issue by NagyWesley** [WPGlobus/WPGlobus#58]
My site is multilanguage AR/EN using WP Globus with nicethemes.com/smart theme , everything is working fine except for strings like "Read more" and "Categories" which are found translated in the .po file... any help?

**Comment by tivnet** [comment]
@NagyWesley 

More details please:

- in which .po file do those strings appear and where the file is located?
- On which page(s) do you see them untranslated? (a link would help)

Thank you!

**Comment by NagyWesley** [comment]
thanks for the quick reply
po file is found in 
/wp-content/languages/ar.po

links: 
- http://antiochglobal.org/welcome-message/
- http://antiochglobal.org/antioch-letters/

**Comment by tivnet** [comment]
Please ask the theme authors if they print those words using WP translation functions.

**Comment by NagyWesley** [comment]
as I see in the code they are already using the translation functions... I've contacted them to check and will keep you posted.

**Comment by NagyWesley** [comment]
wrong file location.. files should be in /wp-content/themes/smart/languages
