### ISSUE TITLE
http://localhost/{language} is not supported

### ISSUE THREAD

**Issue by jl2035** [WPGlobus/WPGlobus#6]
Hello. I guess it's better to post issues here than on wordpress.org, right?

I have the plugin installed and activated. I configured the languages then I added the widget to my sidebar, but all 3 links are the same .. http://localhost/post-title

Also I think the urls don't work. If I visit http://localhost/en/post-title, I get wp 404 error. The menu items get translated to english, but the page is 404. The same if I just visit a url like this:
http://localhost/en  (404 for all 3 languages I have).

WordPress 4.1.1
WpGlobus 1.0.10

**Comment by tivnet** [comment]
Hi @jl2035,

Currently, we do not support 'localhost' as a valid URL. The algorithm we use in WPGlobus to recognize language in URLs looks for a standard http(s)://*.example.tld pattern, and treats all other URLs as either external or invalid - and ignores them.

I believe, we should include `localhost` in the algorithm.

Thank you for your report!

**Comment by jl2035** [comment]
It works if I setup wordpress to run on my local ip (like 192.168.1.15), so ip based url also works..

**Comment by tivnet** [comment]
IP might work, indeed, because .1.15 "looks" like .something.com to the parsing algorithm.

There is a way to "fake" domain name, by using the "hosts" file:

http://wpmututorials.com/how-to/using-a-hosts-file/

**Comment by 594044277** [comment]
jl2035, could you give me some pointers on how to setup wordpress to run on my local ip (like 192.168.1.15), currently I'm running WP in localhost and WPGlobus is not switching languages.

**Comment by tivnet** [comment]
@594044277 Which OS, Windows, Mac, Linux?

**Comment by jl2035** [comment]
@594044277 find your ip (ifconfig on linux or ipconfig on windows), then in wodpress admin settings set this as the application url

**Comment by tivnet** [comment]
As I said before, that's only a workaround. The proper way would be using `hosts` to setup a local domain name. For instance,
    
    127.0.0.1 dev.mysite.com

**Comment by 594044277** [comment]
Win 8.1 /  IIS server. WP 4.1.3 
Assigned 127.0.0.1 to mysite.local for local domain in hosts but my site is in localhost/mysite directory so what else can I do?  mysite.local points to IIS default page. If I type mysite.local/mysite then I get to my site but  WPGlobus still not changing the language.

**Comment by tivnet** [comment]
@594044277 

You can do either:
- If your site is www.mysite.com then use dev.mysite.com for local development. WPGlobus should work. The bad thing here is that if you need to copy database from local to production, you need to change all 'dev' to 'www' in the MySQL dump
- Put 127.0.0.1 www.mysite.com in your 'hosts' file and you will see the local version exactly as you would see the production. DB will be easy to deploy. To make switching easy, you can use http://hostprofiles.codeplex.com/. That's what I do.
- The @jl2035 's workaround: access your local site by IP.
- Wait until the WPGlobus authors add the localhost support... (currently it's in the low priority, because we sincerely believe noone should use localhost)...

Thank you!

**Comment by 594044277** [comment]
@tivnet  One thing I forgot to mention since I was redirected from WP.org WPGlobus forum is that I'm testing site on localhost only no domain yet and its a child theme of Sunrise but from your detail advice I think my best option would be workaround.
Thank you for your knowledge and patience
.

**Comment by tivnet** [comment]
@jl2035 
@594044277 
Please upgrade to the version 1.0.12. It should work with localhost and IP correctly.
Let us know if you still have any issues
Thank you!

**Comment by 594044277** [comment]
@tivnet 
Thanks a lot, all is working great with new version, I also changed permalinks from default to another type as advised in another topic and changed back to localhost instead of local IP workaround.
