### ISSUE TITLE
Yoast SEO 7.7.2 and WPGlobus 1.9.16 not compatibility, can't edit meta title and meta description. Next upgrade ?

### ISSUE THREAD

**Issue by Damskzk** [WPGlobus/WPGlobus#63]
Wordpress version: 4.9.6
WPGlobus version: 1.9.16
Yoast SEO version: 7.7.2

Hello,

I updated WordPress plugins. Since, i have a problem between WPGlobus and Yoast SEO. I can't edit meta title and meta description on all pages.

On wpglobus.com, there is a news on June 26, 2018 (https://wpglobus.com/plugin-updates/wpglobus-update/). When this problem is resolved ?

I need help, because i must to put a website online.

Thanks,
Damien _(sorry for my english)_

![bug-wpglobus-yoastseo](https://user-images.githubusercontent.com/32643605/42153062-486bfda4-7de2-11e8-8851-df5ea8c0ea34.jpg)

**Comment by tivnet** [comment]
Sorry, we cannot issue an upgrade yet. Please use the previous version of
Yoast, compatible with WPGlobus for now.

**Comment by sydro** [comment]
There's same problem with Yoast SEO version: 8.0

**Comment by tivnet** [comment]
You can try the develop branch. We are still testing it.

**Comment by tivnet** [comment]
Released 1.9.17
