### ISSUE TITLE
Custom Fields (Cover Section Title) not translating. 

### ISSUE THREAD

**Issue by baked90** [WPGlobus/WPGlobus#64]
There is already another really similar issue here and I tried to follow up the instructions, but was not able to find a solution for my case...
My Title (editable trough theme-customizer) won't change. It shows:

"{:en}English heading{:}{:de}German Heading{:}" at once:
https://imgur.com/a/4gReBxD

I tried to change the PHP File in Row 105:
https://imgur.com/a/oP64wSW

From "echo $wlow_home_cover_title;" to "echo apply_filters( 'the_title', $post->wlow_home_cover_title );" .. But it's not working... It just deletes the whole title..!

I'm fairly new to PHP and Wordpress indepth customization. I'd love if somebody would help me here!

 Thank you so much in advance!!!!

**Comment by tivnet** [comment]
@baked90 
It should be:
`echo apply_filters( 'the_title', $wlow_home_cover_title );`
without `post->`

That should work.

However, a better fix would be doing it not here but where the home cover title is retrieved from the database. Tell that the theme authors, so they can handle this properly.

**Comment by baked90** [comment]
Thank you so much. It worked. But for the SubTitle & Button there is a different Syntax:

`	/* Subtitle */
				if( !empty($wlow_home_cover_subtitle) ){
					echo '<h3 class="parallax__caption__subtitle large light">'. $wlow_home_cover_subtitle .'</h3>';
				}

				/* Button */
				if( !empty($wlow_home_cover_buttonlabel) ){
					echo '<a class="scroll-to button animate" href="'. $wlow_home_cover_buttonlink .'">'. $wlow_home_cover_buttonlabel .'</a>';`

Do you know an easy fix for these ones? (These are the last elements which are not working for me)

By the way: I contacted the Theme Author last week but didn't get a response yet.

Thank you SO much for your help! I appreciate your work & plugin and will tell others!

**Comment by tivnet** [comment]
Try

`echo '<a class="scroll-to button animate" href="'. $wlow_home_cover_buttonlink .'">'. apply_filters( 'the_title', $wlow_home_cover_buttonlabel ) .'</a>';`
