### ISSUE TITLE
Latest update breaks the language selector when adding a new page: 1.9.17

### ISSUE THREAD

**Issue by jfeyen** [WPGlobus/WPGlobus#67]
When trying to add a new page I am no longer able to select another language tab other then my default before publishing the article. Then once published, the language tabs are now links and hard-refresh the page.

**Comment by gasparteixeira** [comment]
same here.

**Comment by jfeyen** [comment]
That's a horrible user experience... Is there not a way to detect Gutenberg and then active the 'new' language switch process? We are using the addon for wpbakery visual composer, so no Gutenberg for us. Unfortunately we can't upgrade to the latest version with these changes :(

**Comment by tivnet** [comment]
The Bakery is also supported by the core WPGlobus without addons.

For now, we have to stick with this (horrible) UX. Nice people from WP made their move with automatically jumping to Gutenberg on clicking [Edit]. We'll see what will happen with WP5 arrives.
