### ISSUE TITLE
Gutenberg editor erases all languages on publish

### ISSUE THREAD

**Issue by cesarizu** [WPGlobus/WPGlobus#68]
# Steps to reproduce:

1. Edit any page in any language
2. Change some text
3. Publish the changes

# Expected behaviour:

The post is updated and it works.

# What happens

- After publishing, the title of the page changes to "{:en}English Title{:}{:es}Spanish Title{:}".
- On reload all languages are lost except the selected one that has overridden the default language content.

# Versions
WordPress 4.9.8
Gutenberg: 4.1.1
WPGlobus: 1.9.21

**Comment by alexgff** [comment]
@cesarizu 
try deactivate all pluigns except WPGobus and Gutengberg, 
activate standard theme like Twenty Sixteen
 and check

**Comment by cesarizu** [comment]
I've disabled all plugins (only left `gutenberg=4.1.1` and `wpglobus=1.9.22`) and changed the theme to "Twenty Sixteen", but the same error still persists.

When I switch to Spanish I see these cookies:

```
wpglobus-language | en
wpglobus-language-old | en
```

I don't see any param or header specifying that I'm saving the Spanish version of the page.

**Comment by cesarizu** [comment]
After some more tests I can confirm that this is happening on pages only and not with posts. I've tested with `gutenberg=4.0.0` and `gutenberg=4.1.1` and the result is the same. Also I see that the c83ef9b5 commit just mention posts routes and not pages, maybe this is the issue?

**Comment by tivnet** [comment]
@cesarizu Confirmed issue with Gutenberg on pages. Working on a fix.
Thanks for reporting!

**Comment by tivnet** [comment]
@cesarizu Should be fixed in 1.9.23

**Comment by cesarizu** [comment]
I can confirm that 1.9.23 fixes the issue :smile: thanks @tivnet and @alexgff !
