### ISSUE TITLE
Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by francescorenna** [WPGlobus/WPGlobus#69]
Hello guys, can you please help? I'm not able to edit my articles website till I don't deactivate WPGlobus.

Fatal error: Uncaught Error: Call to undefined function acf_maybe_get_field() in /homepages/.../wpglobus/includes/vendor/acf/class-wpglobus-acf.php:85 Stack trace: #0 /homepages/.../wpglobus/includes/class-wpglobus-config-vendor.php(206): WPGlobus_Acf_2::get_post_meta_fields(6065) #1 /homepages/.../wpglobus/includes/class-wpglobus-config-vendor.php(236): WPGlobus_Config_Vendor::get_post_meta_fields('*', Array) #2 /homepages/.../wpglobus/includes/class-wpglobus-config-vendor.php(52): WPGlobus_Config_Vendor::parse_config() #3 /homepages/.../wpglobus/includes/class-wpglobus-config-vendor.php(63): WPGlobus_Config_Vendor->__const in /homepages/.../wpglobus/includes/vendor/acf/class-wpglobus-acf.php on line 85

**Comment by alexgff** [comment]
I am testing ACF 5.7.7, ACF PRO 5.6.9 and WPGlobus 1.9.22
and I don't get this error on my test site.
Please check your versions.

**Comment by alexgff** [comment]
@francescorenna Should be fixed in 1.9.23
