### ISSUE TITLE
Custom Fields (Post Meta) not translating.

### ISSUE THREAD

**Issue by DPerkunas** [WPGlobus/WPGlobus#7]
When in wordpress, screen options "Custom Fields" is checked. It shows text can be translated. However when I try to output the values, the value I see stored is.

"{:en}Custom heading{:}{:zh}Chinese Heading{:}{:ru}Russian Heading{:}{:es}Spanish Heading{:}"

What is the methodology of outputting this without having to do custom regex?

**Comment by tivnet** [comment]
Hi @DPerkunas ,

To output any text having language marks, you can apply, for example, the `the_title` filter:

    echo apply_filters( 'the_title', $string );

It should output the current language's part only.

**Comment by vmartinyan** [comment]
Hi! I'm beginner in WP. I have same problem. In my page I have used for example custom field content1. Where I must insert your above noted filter (echo apply_filters( 'the_title', $string );)
Thanks

**Comment by tivnet** [comment]
@vmartinyan 

If you have a place in the code that looks like

`echo $post->post_title;`

or similar, and you see things like `{:en}` on the screen, then try

`echo apply_filters( 'the_title', $post->post_title );`

**Comment by edsdg** [comment]
Hi,
I have the same problem with custom fields and wp globus.

My code in template:
<?php echo get_post_meta($post->ID, "carrier", true);?>

And I have on my www {:en}{:} etc, how do I filter this? the above solution does not work.

I will be grateful for your help

**Comment by tivnet** [comment]
@edsdg 
Try `<?php echo apply_filters( 'the_title', get_post_meta($post->ID, "carrier", true));?>`

**Comment by edsdg** [comment]
Perfect! Thank you very much :)
