### ISSUE TITLE
WPGlobus does not apply to some Business Directory listing pages

### ISSUE THREAD

**Issue by Swader** [WPGlobus/WPGlobus#71]
When using the popular [business directory plugin](https://wordpress.org/plugins/business-directory-plugin/), I do get the post type listed in WPGlobus settings, but:

- when editing a listing, I lose the ability to switch tab to another language (it's greyed out)
- when publishing a listing, on the main (search) page it will not translate any entries (the language code will remain visible, i.e. `{:en}Category{:}{:hr}Kategorija{:}`)
- on the individual listing page, content of custom listing fields WILL be translated (no visible translation format) but the labels of the fields will not.

Can we expect Business Directory support in WPGlobus?

**Comment by Swader** [comment]
@tivnet @alexgff any info on this?

**Comment by tivnet** [comment]
@Swader Bruno, please contact the Business Directory authors and ask them to filter the strings before outputting them on the screen. Then, WPGlobus will be able to do its job of choosing the right language part of the screen.

**Comment by Swader** [comment]
I see, thanks
