### ISSUE TITLE
Disable builder for custom post type

### ISSUE THREAD

**Issue by nguyen-trung-mulodo** [WPGlobus/WPGlobus#73]
There is a option to disable builder for all post types
![screen shot 2019-01-16 at 10 17 46 am](https://user-images.githubusercontent.com/26378670/51224369-10cab200-1978-11e9-8e32-916549637ba7.png)
But I want to disable builder for only specific post type. Can you help me?

**Comment by alexgff** [comment]
@nguyen-trung-mulodo 
Starting from 2.2.11 version:
   • The Builder mode is turned OFF by default for all custom post types (CPT).
   • To turn on the Builder mode for specific post types, please visit the [Сompatibility] tab.
