### ISSUE TITLE
WPGlobus and ACF Pro gallery/repeater

### ISSUE THREAD

**Issue by Blinks44** [WPGlobus/WPGlobus#74]
Greetings! Thank you for this awesome plugin, but i have one problem, using WPGlobus (latest version) and ACF Pro (5.7.10). In custom post type i have gallery field and after i switch from russian to english version and add data to english, gallery field delete all data... I have to insert data in both languages, disable WPGlobus, insert gallery data on 1 language and then activate plugin again, after that everything works fine, until i touch gallery field on both languages again... So everytime i have to disable WPGlobus to insert data in gallery/repeater.

**Comment by alexgff** [comment]
@Blinks44 
Update WPGlobus to 2.1.7 and check.
