### ISSUE TITLE
WPGlobus. Doesnt't work with hex color in Woostroid theme.

### ISSUE THREAD

**Issue by sergey-prosvirnin** [WPGlobus/WPGlobus#75]
Hello ! I have next problem WPGlobus plugin doesn't work with hex color where is chars (e.g. #857755 will work, #89dd77 not) in Woostroid theme - http://documentation.templatemonster.com/index.php?project=woostroid . But when I off this plugin all value work. Please help me !

GIF description this problem - http://recordit.co/IaamdC9Ju3

Sorry for my English ! Please correct me !

**Comment by alexgff** [comment]
@sergey-prosvirnin 
You should exclude color field from the list that WPGlobus processes in customizer.
Find WPGlobus Settings->Fields Settings, uncheck appropriate field(s) and click Save&Reload button.

**Comment by sergey-prosvirnin** [comment]
Thank you !
