### ISSUE TITLE
Footer copyright not translated 

### ISSUE THREAD

**Issue by 4ingiz** [WPGlobus/WPGlobus#77]
Not correct work footer copyright tranlater. I set 3 languages and see next:
{:uk}Благодійний фонд «Проти Дитячої Лейкемії» © 2019{:}{:ru}Благотворительный фонд «Против Детской Лейкемии» © 2019{:}{:en}Charaity Fund «Against Children's Leukemia»{:}
site: protiv.org.ua

**Comment by alexgff** [comment]
If the theme you chose for your WordPress website uses an options panel, you should activate the WPGlobus Translate Options plugin and configure it as described here.
https://wpglobus.com/extensions-archive/multilingual-texts-in-wordpress-theme-options-panel/

**Comment by 4ingiz** [comment]
Thank you
