### ISSUE TITLE
menu show all flags CSS Help Me

### ISSUE THREAD

**Issue by cagataygursell** [WPGlobus/WPGlobus#78]
Hi dear;

I don't know much of the software. But I need to show all flags in the main menu. only the flag will not be the language names. Can you share a code related to it?

**Comment by alexgff** [comment]
If you need show the flags only you can 
1. select `Flags only` in `Language Selector Mode` option on WPGlobus Options page 
( for  navigation menu )
2.  insert your own language switcher in specific place in the header
https://wpglobus.com/faq/is-there-php-code-to-insert-language-switcher-in-specific-place/
