### ISSUE TITLE
Post meta and "Read more" link not translated

### ISSUE THREAD

**Issue by jl2035** [WPGlobus/WPGlobus#8]
I'm using Responsive Theme from Cyberchimps.
This might not be WPGlobus issue, but I'm not sure if I should ask Responsive Theme support..

I'm want to have 3 languages: slovenian (default), serbian and english

It all works ok on english and serbian. But in slovenian "post meta" (like the word "Author"), discussion and Read More link don't get translated. They appear in english.

I also installed the Localization plugin and checked those translations, but they all look fine. Does this make any sense? What am I to do here?

**Comment by alexgff** [comment]
@jl2035 
What Language Code, Name in English and Locale are you using for slovenian language ?

**Comment by jl2035** [comment]
code: sl
locale: sl-SI
name in english: Slovenian

**Comment by alexgff** [comment]
@jl2035 
try set locale to sl_SL

**Comment by jl2035** [comment]
i just did.. but it didn't fix the problem.. do I need to remove the language and add it again?

**Comment by alexgff** [comment]
remove from dir \wp-content\languages\ files with sl_SI locale
and set up again from admin

**Comment by jl2035** [comment]
this also doesn't help :(

**Comment by tivnet** [comment]
@alexgff 
I just looked at the Responsive demo, and did not see there the word "Author". 

In the code, I do not see it either:
`function responsive_post_meta_data` in https://themes.svn.wordpress.org/responsive/1.9.7.6/core/includes/functions.php

Maybe I am in a wrong place?

**Comment by jl2035** [comment]
I actually modified that function to only display "Author: admin" for example. If I remove my modifications the issue is still there:

Posted on April 14, 2015 by admin

you can find this in /core/includes/functions.php
find the function responsive_post_meta_data(), it should be in the end of the file

**Comment by tivnet** [comment]
@jl2035 So, you see
`__( '<span class="%1$s">Posted on </span>%2$s<span class="%3$s"> by </span>%4$s', 'responsive' ),`
in English, and not in Slovenian, correct?

I see in the translations
`
#: core/includes/functions.php
msgid "<span class=\"%1$s\">Posted on </span>%2$s<span class=\"%3$s\"> by </span>%4$s"
msgstr "<span class=\"%1$s\">Objavljeno </span>%2$s<span class=\"%3$s\"> оd </span>%4$s"
`
So, it should work.

"Author" is not there.

**Comment by jl2035** [comment]
<span class="%1$s">Posted on </span>%2$s<span class="%3$s"> by </span>%4$s

yes I see that in english. let's forget about the "Author" for now. that was my modification.

**Comment by tivnet** [comment]
@jl2035 
- Just curious, your admin interface is EN? What happens if you switch language in wp-admin to Slovenian? Will that message still be in EN?
- You said you have your version in your functions.php, correct? What happens if you `echo` something else there, which does not belong to the 'responsive' text domain?

**Comment by jl2035** [comment]
The word "Author", for example, does not belong to the responsive textdomain but to wordpress default (I also have translation files for that). And yeah.. same problem. It doesn't get translated.

I don't have modified functions.php. I only had the file post-meta.php overridden (where I excluded the call to responsive_post_meta_data). But I removed that file to first fix this issue.

**Comment by tivnet** [comment]
puzzled... need to test all this without WPGlobus, just by setting WP_LANG to non-EN.

**Comment by jl2035** [comment]
Tested! It works ok with WPGlobus disabled.

**Comment by tivnet** [comment]
So, did I understand correctly: you switched WordPress language to Slovenian, and you can see the "Posted on" as "Objavljeno" ?

**Comment by jl2035** [comment]
yes, that's correct

**Comment by tivnet** [comment]
OK. Now, when you turn WPGlobus on, and you do not change anything else, it goes back to English?

**Comment by jl2035** [comment]
yes, the wordpress lang setting actually stayed slovenian, but the post meta and read-more link are not being translated, just like before (still only for slovenian).

**Comment by tivnet** [comment]
Is there a way you can give us full archive of your files and database so we can try to reproduce this locally and debug?

**Comment by jl2035** [comment]
i can do that.. where do I send you the files?

**Comment by tivnet** [comment]
You can put them for example on DropBox or even as a ZIP on your site's server, and send us a private message with the link via www.wpglobus.com/pg/contact-us/
Thank you!

**Comment by jl2035** [comment]
ok.. this will take a few minutes

**Comment by jl2035** [comment]
just sent

**Comment by tivnet** [comment]
Received, will let you know as soon as we find where the problem is. Thanks

**Comment by tivnet** [comment]
@jl2035 Meantime, could you please check one thing: I see that in Settings you have only "site url" and not "home url". That may not be related to your question, but it may affect something else, because our code relies on home url settings.

**Comment by tivnet** [comment]
Ignore home url for now. I checked. It's not related.

**Comment by tivnet** [comment]
@jl2035 
There are two files:
`wp-content/themes/responsive/languages/sl_Sl.mo`
and
`wp-content/themes/responsive/languages/sl_Sl.po`

They should be capitalized as `sl_SL.*`
Rename them, and you'll see `Objavljeno`

**Comment by tivnet** [comment]
We believe, this case is closed. If you still have problems, please reopen the ticket.

Or, if you are completely satisfied, we appreciate a **5-star review**:
https://wordpress.org/support/view/plugin-reviews/wpglobus?filter=5

_Thank you!
The WPGlobus Team_

**Comment by tivnet** [comment]
P.S. Wrote to the Responsive Theme support:
https://wordpress.org/support/topic/please-capitalize-sl_sipomo-properly?replies=1

**Comment by jl2035** [comment]
yeah I had to write a review.. I only get pure awesomeness from you guys :)

**Comment by tivnet** [comment]
Thank you!
