### ISSUE TITLE
excerpt with MORE separator is not translated if the_posts() is not called

### ISSUE THREAD

**Issue by tpokorra** [WPGlobus/WPGlobus#84]
I noticed that on my page, using a theme that only uses have_posts() and then a while loop with the_post(), the excerpt would not be translated, if using the MORE separator.

I found the code in includes/class-wpglobus-filters.php, which solves this issue for the_posts(), but that is not called in my scenario.

Therefore I suggest to add a filter as well for the_post(), which works in my situation.
Or are there any unwanted side effects for other situations?

**Comment by alexgff** [comment]
@tpokorra What theme are you using?

**Comment by tpokorra** [comment]
@alexgff I can see this for example with this theme: 

https://themegrill.com/themes/spacious/
https://downloads.wordpress.org/theme/spacious.zip

The home.php looks like this:

```
<?php
	<?php do_action( 'spacious_before_body_content' ); ?>

	<div id="primary">
		<div id="content" class="clearfix">

			<?php if ( have_posts() ) : ?>

				<?php while ( have_posts() ) : the_post(); ?>
```

There is no call to the_posts(), as far as I can see.

**Comment by alexgff** [comment]
@tpokorra 
I am trying to reproduce the case with `excerpt` using Spacious theme. And I get correct translated excerpt on front without additional filter.

**Comment by tpokorra** [comment]
I guess this was because I used the classic editor. With Gutenberg it works fine.
