### ISSUE TITLE
Exclude some custom fields from translating

### ISSUE THREAD

**Issue by charlenejackie** [WPGlobus/WPGlobus#87]
Is it possible select which custom fields to translate? I want to keep some of them the same for all languages while having the option to translate others.

**Comment by alexgff** [comment]
@charlenejackie 
You can use filter `wpglobus_localize_data` to filter data on post edit page
https://github.com/WPGlobus/WPGlobus/blob/develop/includes/class-wpglobus.php#L1859
To prevent the setting as multilingual field you should add custom field name into $data['excludeCustomFields'] array
