### ISSUE TITLE
Web Stories plugin compatibility: Story view/ preview display and validation issues

### ISSUE THREAD

**Issue by ernee** [WPGlobus/WPGlobus#90]
When using WPGlobus with the [Web Stories plugin](https://wordpress.org/plugins/web-stories/), a variety of display issues can appear on the story (URL). 

The [issue was initially reported](https://github.com/google/web-stories-wp/issues/3583) to our team during the beta period, and it still persists with the stable version now available. 

In the user's case, it prevents the output of the html of the story post leading to [a blank document](https://www.wiccangathering.com/web-stories/wiccan-spells/).

In my own testing, the display of [fonts of my story are affected](https://www.goodbyehello.today/web-stories/test-story/) and quite a number of validation errors are present:
![Screen Shot 2020-10-06 at 7 02 46 PM](https://user-images.githubusercontent.com/8108643/95281463-129f6d80-080c-11eb-8936-a2599112cd5a.png)

Since Web Stories are AMP documents, they must adhere to [the specification](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/) to be valid. The display issues correlate with invalid markup present in the story URL (note we are also working on a way to prevent such errors where we can in https://github.com/google/web-stories-wp/pull/4513). 

Trying to exclude the story post types in the settings doesn't seem to prevent these issues:
<img width="1068" alt="Screen Shot 2020-10-06 at 7 51 26 PM" src="https://user-images.githubusercontent.com/8108643/95282188-c35a3c80-080d-11eb-8f3e-3e86285b93d3.png">

It would be great if the two plugins could work together seamlessly.  Feel free to let us know if any further information is needed.

**Comment by swissspidy** [comment]
Looking at the WPGlobus code, I see two issues:

* `WPGlobus_Filters::filter__the_posts` filters posts even if their post type is disabled in  the settings or via  a filter.
* Using `htmlspecialchars_decode()` in `WPGlobus_Core::text_filter` (which is called by `WPGlobus_Core::translate_wp_post` completely breaks the Web Stories HTML markup.

Changing `$text = htmlspecialchars_decode( $text );` to `$text = htmlspecialchars_decode( $text, ENT_HTML5 );` solves the issue, but the filter shouldn't really run in the first place.

**Comment by tivnet** [comment]
WPglobus version 2.5.15 has the fix: disabled post types are not filtered now. The second suggestion by @swissspidy needs a more detailed investigation.

**Comment by swissspidy** [comment]
Awesome, thanks a lot!
