### ISSUE TITLE
No translation for menu

### ISSUE THREAD

**Issue by vietsystems** [WPGlobus/WPGlobus#91]
the free version works fine, except I get menu not translated, Theme is Traveler, they have a classic layout, with this all is ok, their modern layout still shows me {:en}Contact{:}{:de}Kontakt{:} Can someone point me in a direction, where can I look for that?

**Comment by tivnet** [comment]
Dear @vietsystems 

Theme "Traveler" is a commercial one. We do not have access to it and won't be able to deal with its issues.

Also, please, when you contact our support, make sure you type in your correct email. Otherwise, we won't be able to reply.

Thank you!
