### ISSUE TITLE
Breaks code blocks on posts

### ISSUE THREAD

**Issue by jussikoskinen** [WPGlobus/WPGlobus#92]
Enabling WPGlobus breaks the code blocks in the posts that contain XML tags. It seem to me that code-tag does not escape the code in between the tags and in many times results into an empty block. You just get "This block contains unexpected or invalid content" on those blocks. Disabling the plugin fixes the issue if you did not update the post in between. 

For example
`<color name="BLACK" r="0" g="0" b="0"/>`
will just show an empty block with "This block contains unexpected or invalid content".

Using Version 2.5.16

**Comment by alexgff** [comment]
@jussikoskinen 
A new version has been released with a fix.
