### ISSUE TITLE
Fatal Error when saving WooCommerce config

### ISSUE THREAD

**Issue by dirad** [WPGlobus/WPGlobus#93]
While having WPGlobus 2.5.20 [also in previous version] active in my wordpress 5.5.3, with Woocommerce, saving the settings under the WC page, causes a fatal error:

`Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in www\app\public\wp-content\plugins\wpglobus\includes\admin\recommendations\class-wpglobus-admin-recommendations.php:80 Stack trace: #0 www\app\public\wp-includes\class-wp-hook.php(287): WPGlobus_Admin_Recommendations::for_woocommerce(Array) #1 www\app\public\wp-includes\plugin.php(206): WP_Hook->apply_filters(Array, Array) #2 www\app\public\wp-content\plugins\woocommerce\includes\admin\settings\class-wc-settings-general.php(47): apply_filters('woocommerce_gen...', Array) #3 www\app\public\wp-content\plugins\woocommerce\includes\admin\settings\class-wc-settings-general.php(327): WC_Settings_General->get_settings() #4 www\app\public\wp-includes\class-wp-hook.php(287): WC_Settings_General->save('') #5 www\app\public\wp-includes\class-wp-hook.php(311): WP_Ho in www\app\public\wp-content\plugins\wpglobus\includes\admin\recommendations\class-wpglobus-admin-recommendations.php on line 80`

The settings are not saved, but i am able to reopen the admin page.
The only way to make a settings change is to deactivate WPGlobus, save settings, and reactivate.
This seems to come from the recommendations, which initially felt to me dont belong in the bottom of a Woocommerce page. Maybe as a notification on the top, as usual notices go.

**Comment by tivnet** [comment]
@dirad 

We could not reproduce the issue. Under normal circumstances, the filter applied to `get_settings` in WC Settings General finds the `is_plugin_active()` admin function.

However, I can imagine a situation that some 3rd party code calls `get_settings` in a "weird" way, so we are disabling the WC Recommendations code in 2.5.21 and will refactor it to use admin notices as you suggested.

Thanks for reporting!
